import { Customer, CustomerFormData, CustomerStatus } from '@/types/customer';
import { supabase } from '@/integrations/supabase/client';

/**
 * Save a new customer to Supabase database
 */
export const saveCustomer = async (formData: CustomerFormData): Promise<Customer> => {
    const { data, error } = await supabase
        .from('customers')
        .insert({
            full_name: formData.fullName,
            email: formData.email,
            phone: formData.phone,
            age: parseInt(formData.age),
            gender: formData.gender,
            address: formData.address,
            membership_type: formData.membershipType,
            start_date: formData.startDate,
            customer_id: '', // Will be auto-generated by trigger
            status: 'pending', // Default status for new registrations
            gym_id: formData.gymId || null,
        })
        .select()
        .single();

    if (error) {
        console.error('Error saving customer:', error);
        throw new Error('Failed to save customer: ' + error.message);
    }

    if (!data) {
        throw new Error('No data returned from insert');
    }

    // Convert database format to Customer type
    return {
        id: data.id,
        customerId: data.customer_id,
        fullName: data.full_name,
        email: data.email,
        phone: data.phone,
        age: data.age.toString(),
        gender: data.gender as 'male' | 'female' | 'other',
        address: data.address,
        membershipType: data.membership_type as any,
        startDate: data.start_date,
        createdAt: data.created_at,
        status: (data.status as CustomerStatus) || 'pending',
        gymId: data.gym_id || undefined,
    };
};

/**
 * Get all customers from Supabase database
 */
export const getAllCustomers = async (): Promise<Customer[]> => {
    const { data, error } = await supabase
        .from('customers')
        .select('*')
        .order('created_at', { ascending: false });

    if (error) {
        console.error('Error fetching customers:', error);
        throw new Error('Failed to fetch customers: ' + error.message);
    }

    // Convert database format to Customer type
    return (data || []).map(item => ({
        id: item.id,
        customerId: item.customer_id,
        fullName: item.full_name,
        email: item.email,
        phone: item.phone,
        age: item.age.toString(),
        gender: item.gender as 'male' | 'female' | 'other',
        address: item.address,
        membershipType: item.membership_type as any,
        startDate: item.start_date,
        createdAt: item.created_at,
        status: (item.status as CustomerStatus) || 'pending',
        gymId: item.gym_id || undefined,
    }));
};

/**
 * Get a single customer by ID
 */
export const getCustomerById = async (customerId: string): Promise<Customer | null> => {
    const { data, error } = await supabase
        .from('customers')
        .select('*')
        .eq('customer_id', customerId)
        .single();

    if (error) {
        console.error('Error fetching customer:', error);
        return null;
    }

    if (!data) return null;

    return {
        id: data.id,
        customerId: data.customer_id,
        fullName: data.full_name,
        email: data.email,
        phone: data.phone,
        age: data.age.toString(),
        gender: data.gender as 'male' | 'female' | 'other',
        address: data.address,
        membershipType: data.membership_type as any,
        startDate: data.start_date,
        createdAt: data.created_at,
        status: (data.status as CustomerStatus) || 'pending',
        gymId: data.gym_id || undefined,
    };
};

/**
 * Export customers as CSV string
 */
export const exportCustomersAsCSV = (customers: Customer[]): string => {
    if (customers.length === 0) return '';

    const headers = [
        'Customer ID',
        'Full Name',
        'Email',
        'Phone',
        'Age',
        'Gender',
        'Address',
        'Membership Type',
        'Start Date',
        'Created At',
    ];

    const rows = customers.map(c => [
        c.customerId,
        c.fullName,
        c.email,
        c.phone,
        c.age,
        c.gender,
        c.address,
        c.membershipType,
        c.startDate,
        c.createdAt,
    ]);

    const csvContent = [
        headers.join(','),
        ...rows.map(row => row.map(cell => `"${cell}"`).join(',')),
    ].join('\n');

    return csvContent;
};

/**
 * Subscribe to real-time customer updates
 */
export const subscribeToCustomers = (callback: (customers: Customer[]) => void) => {
    const channel = supabase
        .channel('customers_changes')
        .on(
            'postgres_changes',
            {
                event: '*',
                schema: 'public',
                table: 'customers',
            },
            async () => {
                // Fetch updated customer list
                const customers = await getAllCustomers();
                callback(customers);
            }
        )
        .subscribe();

    return () => {
        supabase.removeChannel(channel);
    };
};

/**
 * Update customer status (pending -> approved -> member)
 */
export const updateCustomerStatus = async (customerId: string, status: CustomerStatus): Promise<void> => {
    const { error } = await supabase
        .from('customers')
        .update({ status })
        .eq('id', customerId);

    if (error) {
        console.error('Error updating customer status:', error);
        throw new Error('Failed to update customer status: ' + error.message);
    }
};

/**
 * Convert customer to member (creates member record and updates status)
 */
export const convertCustomerToMember = async (customerId: string): Promise<void> => {
    // First get the customer details
    const { data: customer, error: fetchError } = await supabase
        .from('customers')
        .select('*')
        .eq('id', customerId)
        .single();

    if (fetchError || !customer) {
        throw new Error('Customer not found');
    }

    // Calculate expiry date based on membership type
    const startDate = new Date(customer.start_date);
    const expiryDate = new Date(customer.start_date);

    const monthsMap: Record<string, number> = {
        '1-month-trial': 1,
        '3-month-basic': 3,
        '6-month-standard': 6,
        '12-month-premium': 12,
    };
    const months = monthsMap[customer.membership_type] || 1;
    expiryDate.setMonth(expiryDate.getMonth() + months);

    // Create member record matching members table schema exactly:
    // id, name, phone, email, photo, plan, start_date, expiry_date, 
    // status, payment_due, address, created_at, updated_at
    const { error: memberError } = await supabase
        .from('members')
        .insert({
            name: customer.full_name,
            phone: customer.phone,
            email: customer.email, // Use customer's actual email
            photo: null, // No photo initially
            plan: customer.membership_type,
            start_date: startDate.toISOString().split('T')[0],
            expiry_date: expiryDate.toISOString().split('T')[0],
            status: 'active',
            payment_due: 0, // No payment due initially
            address: customer.address || null,
        });

    if (memberError) {
        console.error('Error creating member:', memberError);
        throw new Error('Failed to create member: ' + memberError.message);
    }

    // Update customer status to 'member'
    await updateCustomerStatus(customerId, 'member');
};
